[
  {
    "id": "inv-001",
    "invoiceNumber": "INV-1703980800001",
    "customerId": "cust-001",
    "customerName": "Acme Corporation",
    "customerEmail": "billing@acme.com",
    "customerAddress": "123 Business Ave, Suite 100, New York, NY 10001",
    "items": [
      {
        "description": "Monthly Software License",
        "quantity": 10,
        "price": 49.99
      },
      {
        "description": "Premium Support Package",
        "quantity": 1,
        "price": 199
      }
    ],
    "total": 698.9,
    "balance": 0,
    "status": "paid",
    "recurringType": "monthly",
    "dueDate": "2024-01-15T00:00:00.000Z",
    "notes": "January 2024 invoice",
    "createdAt": "2024-01-01T00:00:00.000Z",
    "sentAt": "2024-01-01T10:15:00.000Z",
    "paidAt": "2024-01-10T14:30:00.000Z",
    "paymentMethod": "Bank Transfer",
    "paymentReference": "ACH-20240110-001"
  },
  {
    "id": "inv-002",
    "invoiceNumber": "INV-1703980800002",
    "customerId": "cust-002",
    "customerName": "TechStart Inc.",
    "customerEmail": "accounts@techstart.io",
    "customerAddress": "456 Innovation Drive, San Francisco, CA 94102",
    "items": [
      {
        "description": "Consulting Services (per hour)",
        "quantity": 20,
        "price": 150
      }
    ],
    "total": 3000,
    "balance": 3000,
    "status": "sent",
    "recurringType": "weekly",
    "dueDate": "2024-01-22T00:00:00.000Z",
    "notes": "Week of January 8-12, 2024",
    "createdAt": "2024-01-15T00:00:00.000Z",
    "sentAt": "2024-01-15T09:00:00.000Z",
    "paidAt": null,
    "reminderCount": 1,
    "lastReminderAt": "2024-01-25T10:00:00.000Z"
  },
  {
    "id": "inv-003",
    "invoiceNumber": "INV-1703980800003",
    "customerId": "cust-004",
    "customerName": "Metro Design Studio",
    "customerEmail": "finance@metrodesign.co",
    "customerAddress": "321 Creative Blvd, Floor 5, Chicago, IL 60601",
    "items": [
      {
        "description": "Website Hosting (Enterprise)",
        "quantity": 1,
        "price": 299
      },
      {
        "description": "CDN Bandwidth (TB)",
        "quantity": 5,
        "price": 45
      },
      {
        "description": "SSL Certificate",
        "quantity": 1,
        "price": 79
      }
    ],
    "total": 603,
    "balance": 603,
    "status": "sent",
    "recurringType": "monthly",
    "dueDate": "2024-01-31T00:00:00.000Z",
    "notes": "January 2024 hosting services",
    "createdAt": "2024-01-01T00:00:00.000Z",
    "sentAt": "2024-01-02T08:30:00.000Z",
    "paidAt": null
  },
  {
    "id": "draft-001",
    "invoiceNumber": "INV-1704067200001",
    "customerId": "cust-001",
    "customerName": "Acme Corporation",
    "customerEmail": "billing@acme.com",
    "customerAddress": "123 Business Ave, Suite 100, New York, NY 10001",
    "items": [
      {
        "description": "Monthly Software License",
        "quantity": 10,
        "price": 49.99
      },
      {
        "description": "Premium Support Package",
        "quantity": 1,
        "price": 199
      }
    ],
    "total": 698.9,
    "balance": 698.9,
    "status": "sent",
    "recurringType": "monthly",
    "dueDate": "2024-02-15T00:00:00.000Z",
    "notes": "Auto-generated monthly invoice. Please review and edit before sending.",
    "createdAt": "2024-02-01T00:00:00.000Z",
    "sentAt": "2026-04-27T13:53:39.918Z",
    "paidAt": null,
    "autoGenerated": true
  }
]